### ISSUE TITLE
GO Install?

### ISSUE THREAD

**Issue by adam-rocska** [cloudprivacylabs/lsa#76]
I don't speak Go at all, so sorry if it's a dumb-dumb... but shouldn't this work?
```
rocskaadam@Rocska-MBP schema-dts % go install github.com/cloudprivacylabs/lsa@latest
go: github.com/cloudprivacylabs/lsa@latest: module github.com/cloudprivacylabs/lsa@latest found (v1.0.0), but does not contain package github.com/cloudprivacylabs/lsa
```

I did manage to install the same way [json2rdf](https://github.com/cloudprivacylabs/json2rdf)

**Comment by bserdar** [comment]
The runnable binary is under /layers, so `go install github.com/cloudprivacylabs/lsa/layers@latest` should work. It will install the `layers` binary.

You can also download one of the available binary releases.

**Comment by adam-rocska** [comment]
OMG. Thank you. 
I really should find some time to _go_ and learn at least the basics.

🤷🙏
